### ISSUE TITLE
Using JS now

### ISSUE THREAD

**Issue by JasonThomasData** [planningalerts-scrapers/griffith#1]
Hi, not a huge Ruby user but here's what I've figured out - 

This page is now using JS to render the results. Did it do that before? The old link this scraper uses redirects the request to the new page. Also the button click in Mechanise is still working.

The results are loaded in a panel that doesn't show up if JS is turned off.

**Comment by LoveMyData** [comment]
Code updated, pending PR #2 approval

**Comment by LoveMyData** [comment]
Fixed with https://github.com/planningalerts-scrapers/griffith/commit/9c6d3c9086ddb7251efb74948e828adddd8043c1
